### Delete Car - Manual Test
DELETE http://localhost:3000/api/cars/00000000-0000-0000-0000-000000000000
# Authorization: Bearer {{token}}
Content-Type: application/json

{
  "confirmation_name": "My Audi A4"
}
